name: Translate SAS files

on:
  push:
    paths:
      - "original-sas-code/*.sas"

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Add other dependencies if necessary

      - name: Translate SAS file
        run: python tsql-convert.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://${{ secrets.GH_TOKEN }}@github.com/jrthartwig/sas-tsql-demo.git
          git add modified-sas-code/*.sas
          git commit -m "Translated SAS files" || echo "No changes to commit"
          git push
